docs: Mbed CLI 2
ARMmbed/mbed-tools pull request #100
Opened 2020-10-28 14:20 UTC by jainvikas8

### Description

Update the documentation to reflect the following changes:
* `mbed-tools` will be officially called as Mbed CLI 2. `mbed-tools` is
the python package name
* BLE button example is not supported by Mbed OS 6.4.0 onwards,
therefore recommend using BLE LED instead.
* Reworded few sentences

### Test Coverage

- [x]  This change is covered by existing or additional automated tests.
- [ ]  Manual testing has been performed (and evidence provided) as automated testing was not feasible.
- [ ]  Additional tests are not required for this change (e.g. documentation update).

2020-10-28 14:24 UTC, Patater requested changes

2020-10-28 14:24 UTC, Patater commented on docs/howto/mbed-tools-howto.md
> +- Cmake. [Install version 3.18.1 or newer for all operating systems](https://cmake.org/install/).
```diff
- Cmake
+ CMake
```

2020-10-28 14:24 UTC, Patater commented on docs/howto/mbed-tools-howto.md
> +You can use a single command to configure (set up your target and toolchain) and build the project at once:
```diff
- set up
+ select
```

2020-10-28 14:29 UTC, jainvikas8 commented
Forced pushed to address changes from @Patater

2020-10-28 14:37 UTC, Patater approved these changes

2020-10-28 15:12 UTC, merged

2020-11-14 17:43 UTC, 40Grit commented
Personally i thought mbed-tools to be quite fitting.

Mbed Development Tools (MDT)