config: Add CMake variable for the path o the local Mbed OS program
ARMmbed/mbed-tools pull request #103
Opened 2020-11-04 13:02 UTC by hugueskamba

MBED_ROOT is provided in the generated configuration CMake module.

### Description

### Test Coverage

- [x]  This change is covered by existing or additional automated tests.
- [ ]  Manual testing has been performed (and evidence provided) as automated testing was not feasible.
- [ ]  Additional tests are not required for this change (e.g. documentation update).

2020-11-04 13:41 UTC, rwalton-arm requested changes

2020-11-04 13:41 UTC, rwalton-arm commented on src/mbed_tools/build/_internal/cmake_file.py
> +    mbed_target_name: str, target_build_attributes: dict, config: Config, toolchain_name: str, mbed_os_path: str
`mbed_os_path` is a `pathlib.Path` and not a `str`. This is the reason `mypy` is failing in the CI.

2020-11-04 13:47 UTC, Patater requested changes
"MBED_ROOT is provided in the generated configuration CMake module."

But why is this useful? Isn't it always relative to the application root at `mbed-os`? The commit message needs to explain the motivation for the change a bit more.

2020-11-04 15:27 UTC, hugueskamba commented
> "MBED_ROOT is provided in the generated configuration CMake module."
> 
> But why is this useful? Isn't it always relative to the application root at `mbed-os`? The commit message needs to explain the motivation for the change a bit more.

We supposed that users can decide to put `mbed-os` to a location other than the app root. One could put it in `<APP_NAME>/libs/mbed-os` . Would the tools generate the config file if ran at `<APP_NAME>`?

Currently every application [create a `MBED_ROOT` CMake variable](https://github.com/ARMmbed/mbed-os-example-blinky/blob/feature-cmake/CMakeLists.txt#L7), this PR creates it instead. However, if we think it is always guaranteed to be at the app root then applications can simple use `add_subdirectory(mbed-os)`.

@0xc0170 thoughts?

2020-11-04 16:48 UTC, Patater commented
> It is used by application programs to add the subdirectory where the Mbed OS program is located.

I still don't understand why application programs would need an MBED_ROOT variable to do this, as the application would know better than the tools would where the mbed-os folder is for add_subdirectory.

2020-11-05 12:05 UTC, hugueskamba commented
Won't change.

2020-11-05 12:05 UTC, closed without merging