ci: Remove Python3.7 from test matrix
ARMmbed/mbed-tools pull request #166
Opened 2021-01-12 15:54 UTC by wernerlewis

### Description

Remove Python 3.7 testing in Tox and CI as it is no longer considered a primary configuration.

Fixes #165 
### Test Coverage

- [x]  This change is covered by existing or additional automated tests.
- [ ]  Manual testing has been performed (and evidence provided) as automated testing was not feasible.
- [ ]  Additional tests are not required for this change (e.g. documentation update).

2021-01-12 16:14 UTC, jeromecoutant commented
Hi
This PR is quite strange as 3.7 is the recommended version...
https://os.mbed.com/docs/mbed-os/v6.6/build-tools/install-and-set-up.html

2021-01-13 10:33 UTC, rwalton-arm commented
> Hi
> This PR is quite strange as 3.7 is the recommended version...
> https://os.mbed.com/docs/mbed-os/v6.6/build-tools/install-and-set-up.html

They are the docs for the old mbed-cli. We are still supporting python3.7 but we're removing it from the CI to reduce churn. We test 3.6, 3.8 and the latest python as they are the versions supplied with ubuntu/homebrew.

2021-01-13 10:34 UTC, rwalton-arm requested changes
Please tidy up the commit history.

2021-01-13 11:16 UTC, Patater approved these changes
LGTM

2021-01-13 11:17 UTC, rwalton-arm approved these changes
LGTM

2021-01-13 11:17 UTC, merged