Improvements to config subcommand
ARMmbed/mbed-tools pull request #288
Opened 2021-05-25 13:50 UTC by g-arjones

### Description

Fixes #287
Fixes #286 

### Test Coverage

- [x]  This change is covered by existing or additional automated tests.
- [ ]  Manual testing has been performed (and evidence provided) as automated testing was not feasible.
- [ ]  Additional tests are not required for this change (e.g. documentation update).

2021-05-26 12:47 UTC, rwalton-arm commented
Thanks for the PR. Could you squash the commit "Fix flake8 linter offenses" so the history is clean? We merge the patchset as is, and we'd prefer not to have "fixup" commits in the history. You'll also need to rebase as the branch is out of date with the base branch.

2021-05-26 13:26 UTC, g-arjones commented
No problem. Updated...

2021-05-27 10:48 UTC, Patater requested changes
Please update the commit messages with an explanation of what motivates the change and any information about why your chosen method to solve the problem is preferable.

2021-05-27 10:48 UTC, Patater commented on news/20210525103622.bugfix
> +Properly handle --custom-targets-json in configure sub command
Could you please rename this file to `286.bugfix`?

2021-05-27 10:48 UTC, Patater commented on news/20210525104111.bugfix
> +Allow choosing output directory in configure sub command
Please rename this to `287.bugfix`. Thanks!

2021-05-27 10:48 UTC, Patater commented on tests/cli/test_configure.py
> +        self.assertEqual(program.files.custom_targets_json, custom_targets_json_path)
GitHub is showing removal of newline at the end of the file. Could you please add it back in commit "config: Handle --custom-targets-json"?

2021-05-27 13:37 UTC, g-arjones commented
Done.

2021-06-01 11:56 UTC, g-arjones commented
Did I miss anything?

2021-06-03 10:31 UTC, rwalton-arm reviewed
Looks good to me. Just needs to be rebased and then we can merge.

2021-06-03 18:38 UTC, g-arjones commented
Rebased.

2021-06-04 08:24 UTC, rwalton-arm commented
We had an automated release this morning and the branch is out of date again. Sorry! If you could rebase one more time we will get this in today.

2021-06-04 11:52 UTC, g-arjones commented
Rebased, again.

2021-06-04 12:14 UTC, rwalton-arm approved these changes

2021-06-04 12:16 UTC, merged