config: Increase click package required version to 8.1
ARMmbed/mbed-tools pull request #327
Opened 2022-07-20 09:18 UTC by ATmobica

### Description

The latest version (8.1.3) of the click package is supported in many
projects. E.g. in CHIP project where mbed-os port is implemented.
https://github.com/project-chip/connectedhomeip
In this case, we need to increase the limit of the click version to 8.1.

### Test Coverage

- [x]  This change is covered by existing or additional automated tests.
- [ ]  Manual testing has been performed (and evidence provided) as automated testing was not feasible.
- [ ]  Additional tests are not required for this change (e.g. documentation update).

2022-07-20 09:19 UTC, ATmobica commented
@pan- link to this PR

2022-07-20 09:37 UTC, pan- approved these changes

2022-07-28 09:17 UTC, Patater requested changes

2022-07-28 09:17 UTC, Patater commented on setup.py
> +        "Click>=7.1,<=8.1",
Please use <9, as we expect any 8.x version to be OK. The current `<8` is meant to say "any future compatible version". If we are compatible with 8.1 now, with your changes, we should be good to go until 9.x.

2022-07-28 13:02 UTC, Patater approved these changes

2022-07-28 13:41 UTC, merged